# -*- coding: utf-8 -*-
"""Session 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f_aLDere5MDKsLlvzHd4QnfLzOYTRY0F
"""

responses = {
    "hi" : "Hello there!",
    "how are you!" : "I'm a bot, I'm always good !"
  }
user_input = "how are you?"
print(responses.get(user_input.lower(), "I don't understand that."))

user_input = input("Enter a query:")

def hello(name):
  print("Hi", name)

name = input("Enter your name: ")
hello(name)

def add_sub(a, b):
  sum = a + b
  diff = a - b
  return sum, diff

num1 = int(input("Enter a number"))
num2 = int(input("Enter a number"))
total, sub = add_sub(num1, num2)
print(total)
print(sub)

import numpy as np

list_sample = [5,6,7,8]
numpy_array = np.array(list_sample)
numpy_array

numpy_array = np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
numpy_array

from numpy import random

arr = random.randint(100)
arr

from numpy import random
arr = random.randint(1000)
arr

from numpy import random
arr1 = random.randint(8)
arr1

from numpy import random
arr-random,randint(100,size(5))
arr-random



'''
Exercise-1
Ask the user to input a random number. Multiply this number by 2 and print it.
'''

# Type your solution below


'''
Exercise-2
Chatbot: (a) Ask a user how they are feeling by printing on screen "How are you feeling today".
(b) After the user provides a input, print on screen "You are feeling " + "<input from user>" + "today".
'''

# Type your solution below